---
title: "Untitled"
author: "Akhilesh Huria"
date: "2023-02-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(rpart)
library(randomForest)
library(readxl)
library(e1071)
library(class)
library(glmnet)
```


```{r}
file_pathtrain2 <- file.choose()
```

```{r}

training_datachallenge2 <- read_excel(file_pathtrain2)

```


```{r}
file_pathtest2 <- file.choose()

```

```{r}
test_datachallenge2 <- read_excel(file_pathtest2)
```


```{r}
Xtraining <- as.matrix(training_datachallenge2[,-1])
Ytraining <- as.matrix(training_datachallenge2[,1])

```


```{r}
lassomodel2 <- glmnet(as.matrix(Xtraining), Ytraining, family = "gaussian", alpha = 1)

```



```{r}
#Now that we have loaded in both the training data - to which a LASSO has been applied - and our test data, we can predict the outcome of the test data.

lassopredict2 <- predict(lassomodel2, newx = as.matrix(test_datachallenge2), type = "response")[, 100]

```



```{r}


write.csv(lassopredict2, "test_data2_LASSOFinal.csv")
```


