---
title: "Untitled"
author: "Akhilesh Huria"
date: "2023-02-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rpart)
library(randomForest)
library(readxl)
library(class)
library(glmnet)
```

```{r}
file_pathtrain1 <- file.choose()
```

```{r}
#We will first load the training data from our file path as seen above.

training_datachallenge1 <- read_excel(file_pathtrain1)

#We can then try and fit the data to different models and evaluate their effectiveness on the test data. But first we need to make sure we have 
```


```{r}
file_pathtest1 <- file.choose()

```

```{r}
test_datachallenge1 <- read_excel(file_pathtest1)
```

```{r}
training_datachallenge1$y <- factor(training_datachallenge1$y)

```


```{r}
#Attempting with other models - Decision Tree Model
RFmodel1 <- randomForest(y ~ ., data = training_datachallenge1, importance = TRUE, replace = TRUE)
```

```{r}
RFprediction1 <- predict(RFmodel1, newdata = test_datachallenge1)
```

```{r}


write.csv(RFprediction1, "test_data1_RFFinalwithbagging.csv")
```


```{r}
test_datachallenge2$RFprediction <- RFprediction2

write.csv(test_datachallenge2, "part2test_data_withRFpredictions.csv")
```
