---
title: "Untitled"
author: "Akhilesh Huria"
date: "2023-02-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rpart)
library(randomForest)
library(readxl)
library(e1071)
library(class)
library(glmnet)
```

```{r}
file_pathtrain2 <- file.choose()
```

```{r}
#We will first load the training data from our file path as seen above.

training_datachallenge2 <- read_excel(file_pathtrain2)

#We can then try and fit the data to different models and evaluate their effectiveness on the test data. But first we need to make sure we have 
```


```{r}
file_pathtest2 <- file.choose()

```

```{r}
test_datachallenge2 <- read_excel(file_pathtest2)
```

```{r}
Xtraining <- as.matrix(training_datachallenge1[-1,-1])
Ytraining <- as.matrix(training_datachallenge1[-1,1])

```


```{r}
#Attempting with other models - Decision Tree Model
SVMmodel2 <- svm(Xtraining, Ytraining, type = "C-classification", kernel = "linear", decision.values = TRUE)

```

```{r}
SVMprediction2 <- predict(SVMmodel2, test_datachallenge2)
```



```{r}
test_datachallenge2$SVMprediction <- SVMprediction2

write.csv(test_datachallenge2, "part2test_data_withSVMpredictions.csv")
```
